# Page settings
baseurl = "https://www.ralrecsoc.com"
title = "RAL Recreational Society"
languageCode = "en-us"
theme = "elate"

# Disable generation of taxonomies
disableKinds = ['taxonomy', 'term']

[params]

  # Meta
  author = "RAL RecSoc Committee"
  description = "Website for the RAL Recreational Society"
  email = "RecSocCommittee@stfc.ac.uk"

  # Google Maps Javascript API Key (if not set will default to not passing a key)
  googleMapsApiKey = ""

  # Navigation
  [params.navigation]
    brand = "RAL RecSoc"
    home = "Home"
    contact = "Contact"
    #
    # # You can add custom links before or after the default links
    # # Assign a weight to define the order
    #
    # prepended links
    # [[menu.prepend]]
    #   url = "/"
    #   name = "Home"
    #   weight = 1
    [[menu.postpend]]
      url = "/join/"
      name = "Join"
      weight = 5
    [[menu.postpend]]
      url = "/clubs/"
      name = "Clubs & Activities"
      weight = 10
    [[menu.postpend]]
      url = "/lounge/"
      name = "The R58 Lounge"
      weight = 20
    [[menu.postpend]]
      url = "/faq/"
      name = "FAQ"
      weight = 30

  # Hero section
  [params.hero]
    title = "Health. Wellbeing. Balance."
    subtitle = 'The RAL Recreational Society exists to provide the staff of [STFC Rutherford Appleton Laboratory](https://www.ukri.org/about-us/stfc/locations/rutherford-appleton-laboratory/) and the surrounding [Harwell Campus](https://www.harwellcampus.com/) health, wellbeing, and sports facilities in order to provide a much needed balance to the world-class science, technology, and engineering we produce.'
    background-image = "bg.jpg"

  # Intro section
  # Available icons from Simple Line Icons (https://simplelineicons.github.io/)
  [params.intro]

  [[params.intro.item]]
    title = "Sports"
    description = "From our on-site gym and sports hall to our external tennis courts, there's sure to be something to help you get active."
    url = "/clubs"
    button = "Learn More"
    icon = "icon-trophy"
    img = "img_7.jpg"

  [[params.intro.item]]
    title = "Recreation"
    description = "Express yourself with paint, a musical instrument, or dance and yoga - we have clubs to suit a wide variety of pursuits."
    url = "/clubs"
    button = "Learn More"
    icon = "icon-puzzle"
    img = "img_8.jpg"

  [[params.intro.item]]
    title = "Social"
    description = "The RecSoc Lounge is available to book for work meetings, leaving parties, and social events, and is fully licensed."
    url = "/lounge"
    button = "Learn More"
    icon = "icon-people"
    img = "img_10.jpg"

  # Contact section
  [params.contact]
    enable = true
    map = true
    form = false
    title = "Contact Us"
    description = "How to contact us, and where to find us."

    details = [
        ["icon-home", "RAL Recreational Society, STFC Rutherford Appleton Laboratory, Building R58, Harwell Campus, Oxfordshire, OX11 0QX"],
        ["icon-envelope", "RecSocCommittee@stfc.ac.uk"]
      ]

  # Footer section
  [params.footer]
    enable = true
    copyright = '&copy; RAL Recreational Society 2022. All Rights Reserved. Uses the _Elate_ theme created by <a href="http://freehtml5.co/" target="_blank">FREEHTML5.co</a> and ported to Hugo by <a href="https://github.com/saey55" target="_blank">saey55</a>'
    links = [
        ["icon-facebook", "https://www.facebook.com/groups/315928308552499/"],
      ]
