name: PR

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - '*'

env:
  HUGO_VERSION: '0.98.0'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Install Prerequisites
      run: |
        set -ex
        wget https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_extended_${HUGO_VERSION}_Linux-64bit.deb -O ${RUNNER_TEMP}/hugo.deb
        sudo dpkg -i ${RUNNER_TEMP}/hugo*.deb
        sudo npm install -g link-checker
    - name: Build Site
      run: |
        set -ex
        npm install
        hugo
    - name: Check Links
      run: |
        set -ex
        link-checker --disable-external public/
