name: Web

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - '*'

env:
  HUGO_VERSION: '0.98.0'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Install Prerequisites
      run: |
        set -ex
        # hugo
        wget https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_extended_${HUGO_VERSION}_Linux-64bit.deb -O ${RUNNER_TEMP}/hugo.deb
        sudo dpkg -i ${RUNNER_TEMP}/hugo*.deb
        # htmltest
        curl https://raw.githubusercontent.com/wjdp/htmltest/master/godownloader.sh | sudo bash -s -- -b /usr/local/bin
    - name: Generate Site
      run: |
        set -ex
        hugo
    - name: Check links
      run: |
        set -ex
        htmltest
    - name: Upload
      if: github.ref == 'refs/heads/main'
      env:
        #HOST_ID: ${{ secrets.SERVER_IDENTITY }}    OLD
        #HOST_IP: ${{ secrets.SERVER_IP }}   OLD
        #HOST_DEST_DIR: ${{ secrets.SERVER_DIRECTORY }}   OLD
        #USER_NAME: ${{ secrets.UPLOADER_NAME }}   OLD
        #USER_ID: ${{ secrets.UPLOADER_IDENTITY }}   OLD
        HOST_ID: ${{ secrets.SERVER_HOST_KEY }}
        HOST_IP: ${{ secrets.SERVER_IP_ADDRESS }}
        HOST_DEST_DIR: ${{ secrets.SERVER_DESTINATION_DIR }}
        USER_NAME: ${{ secrets.SERVER_USER }}
        USER_ID: ${{ secrets.SERVER_USER_CREDENTIALS }}
      run: |
        echo "$USER_ID" > ./id_rsa
        chmod 0600 ./id_rsa
        echo "$HOST_ID" > ./host_id
        rsync -axz --delete -e "ssh -o UserKnownHostsFile=./host_id -i ./id_rsa -p 2212 -l $USER_NAME" public/ ${HOST_IP}:${HOST_DEST_DIR}
