name: PR

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - '*'

env:
  HUGO_VERSION: '0.98.0'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Install Prerequisites
      run: |
        set -ex
        # hugo
        wget https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_extended_${HUGO_VERSION}_Linux-64bit.deb -O ${RUNNER_TEMP}/hugo.deb
        sudo dpkg -i ${RUNNER_TEMP}/hugo*.deb
        # htmltest
        curl https://raw.githubusercontent.com/wjdp/htmltest/master/godownloader.sh | sudo bash -s -- -b /usr/local/bin
    - name: Generate Site
      run: |
        set -ex
        hugo
    - name: Check links
      run: |
        set -ex
        htmltest
